export const USER_CONNECT = 'USER_CONNECT'
export const NEW_USER_CONNECT = 'NEW_USER_CONNECT'
export const USER_DISCONNECT = 'USER_DISCONNECT'
export const USER_READY = 'USER_READY'
export const USER_PROFILE = 'USER_PROFILE'

export const GAME_START = 'GAME_START'
export const ACTIVE_PLAYER = 'ACTIVE_PLAYER'
export const USER_BET = 'USER_BET'
export const ENEMY_BET = 'ENEMY_BET'
export const DELETE_DIBS = 'DELETE_DIBS'
export const TIMER = 'TIMER'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const ENEMY_GET_CARD = 'ENEMY_GET_CARD'
export const GAME_RESULT = 'GAME_RESULT'
export const GAME_END = 'GAME_END'

export const HAND_SUCCESS = 'HAND_SUCCESS'
export const DEAL_HAND = 'DEAL_HAND'
export const PLAY_HAND = 'PLAY_HAND'
export const USER_DATA_UPDATE = 'USER_DATA_UPDATE'
export const ENOUGH_HAND = 'ENOUGH_HAND'